version: "3.8"

services:
  percona-mysql:
    image: percona/percona-server:8.0.35-aarch64
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  proxysql:
    image: percona/proxysql2:2.7.3
    # Force ProxySQL to load from your config file on startup
    command: ["proxysql", "-f", "-c", "/etc/proxysql.cnf", "--initial"]
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
      - ./certs:/certs
    ports:
      - "6033:6033"
      - "6032:6032"
    depends_on:
      - percona-mysql
